import Header from '@/components/header/Header';
import './globals.css';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body
        className={inter.className}
        style={{
          backgroundColor: 'black',
          paddingInline: '5rem',
          paddingTop: '2rem',
        }}
      >
        <Header />
        {children}
      </body>
    </html>
  );
}
